function rad = radadvuni(Zter, Gter, dl, emis, meio, meiofron)

csb = 5.6697e-8;           %Constante de Steffan-Boltzman
rad = emis(meio)*emis(meiofron)*csb/...
    (emis(meio) + emis(meiofron) - emis(meio)*emis(meiofron))...
    *Zter(meio)/(Zter(meio)*Gter(meio) + 2);