function coetrans = transfrontuni(meio, Rter, Zter, Gter, meiofron, Temp, IF)
coetrans = 2*(Zter(meio))/...
    (Rter(meio) + Rter(meiofron) + Zter(meio) + Zter(meiofron))*...
    ((2 - Zter(meiofron)*Gter(meiofron))*Temp + Zter(meiofron)*IF(meiofron))/4;
end